services:
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=medium-int8
      - WHISPER_BEAM=5          # optional: balance speed & accuracy
      - WHISPER_LANG=auto       # optional: auto-detect language
      - LOCAL_ONLY=true         # only use local models, no downloading
    volumes:
      - ./models/transcript-engine:/config
    ports:
      - 10300:10300
    restart: unless-stopped